"""Initial schema

Revision ID: d3e47268af94
Revises: 
Create Date: 2026-04-05 02:16:10.577766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3e47268af94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laws',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('law_name', sa.String(), nullable=False),
    sa.Column('law_type', sa.String(), nullable=False),
    sa.Column('ministry', sa.String(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laws_id'), 'laws', ['id'], unique=False)
    op.create_index(op.f('ix_laws_law_name'), 'laws', ['law_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('law_versions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('law_id', sa.BigInteger(), nullable=False),
    sa.Column('version_label', sa.String(), nullable=False),
    sa.Column('promulgation_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('amended_type', sa.String(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('previous_version_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['law_id'], ['laws.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_versions_id'), 'law_versions', ['id'], unique=False)
    op.create_table('qa_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('intent_type', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('retrieved_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_answer', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_logs_id'), 'qa_logs', ['id'], unique=False)
    op.create_table('law_articles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('law_version_id', sa.BigInteger(), nullable=False),
    sa.Column('article_key', sa.String(), nullable=False),
    sa.Column('article_no', sa.String(), nullable=False),
    sa.Column('paragraph_no', sa.String(), nullable=True),
    sa.Column('item_no', sa.String(), nullable=True),
    sa.Column('subitem_no', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['law_version_id'], ['law_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_articles_article_key'), 'law_articles', ['article_key'], unique=False)
    op.create_index(op.f('ix_law_articles_id'), 'law_articles', ['id'], unique=False)
    op.create_table('law_version_diffs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('law_id', sa.BigInteger(), nullable=False),
    sa.Column('old_version_id', sa.BigInteger(), nullable=False),
    sa.Column('new_version_id', sa.BigInteger(), nullable=False),
    sa.Column('article_key', sa.String(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('old_article_id', sa.BigInteger(), nullable=True),
    sa.Column('new_article_id', sa.BigInteger(), nullable=True),
    sa.Column('old_text', sa.Text(), nullable=True),
    sa.Column('new_text', sa.Text(), nullable=True),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['law_id'], ['laws.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_version_id'], ['law_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['old_version_id'], ['law_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_version_diffs_article_key'), 'law_version_diffs', ['article_key'], unique=False)
    op.create_index(op.f('ix_law_version_diffs_id'), 'law_version_diffs', ['id'], unique=False)
    op.create_table('law_chunks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('qdrant_point_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['law_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_chunks_id'), 'law_chunks', ['id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('choices_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answer_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['law_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_id'), 'quiz_questions', ['id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('user_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_id'), 'quiz_attempts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_attempts_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_quiz_questions_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_law_chunks_id'), table_name='law_chunks')
    op.drop_table('law_chunks')
    op.drop_index(op.f('ix_law_version_diffs_id'), table_name='law_version_diffs')
    op.drop_index(op.f('ix_law_version_diffs_article_key'), table_name='law_version_diffs')
    op.drop_table('law_version_diffs')
    op.drop_index(op.f('ix_law_articles_id'), table_name='law_articles')
    op.drop_index(op.f('ix_law_articles_article_key'), table_name='law_articles')
    op.drop_table('law_articles')
    op.drop_index(op.f('ix_qa_logs_id'), table_name='qa_logs')
    op.drop_table('qa_logs')
    op.drop_index(op.f('ix_law_versions_id'), table_name='law_versions')
    op.drop_table('law_versions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_laws_law_name'), table_name='laws')
    op.drop_index(op.f('ix_laws_id'), table_name='laws')
    op.drop_table('laws')
    # ### end Alembic commands ###
